# Generated by Django 4.1 on 2022-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='defaults/noimage.png', upload_to='products/%Y/%m/%d/'),
        ),
    ]
